import type { CompositionEntry } from '../types/nutrition';

// İlk milestone — 50 yaygın Türk gıdası, per 100g.
// Kaynaklar: TürKomp (TÜBİTAK MAM), USDA FoodData Central.
// Form 'raw' ise pişirme yield faktörü motor tarafından uygulanır.
// Form 'cooked' ise yield atlanır (değer zaten pişmiş gıda için).

export const FOOD_COMPOSITION: CompositionEntry[] = [
  // --- TAHILLAR (raw, yield uygulanır) ---
  {
    id: 'rice_white_raw',
    nameTr: 'Pirinç (çiğ)',
    synonyms: ['pirinç pilavı', 'beyaz pirinç', 'pilavlık pirinç', 'pilav'],
    category: 'grain',
    form: 'raw',
    per100g: { kcal: 360, protein: 6.6, carbs: 79, fat: 0.6, fiber: 1.3 },
    defaultTexture: 'granular',
    source: 'usda',
  },
  {
    id: 'bulgur_raw',
    nameTr: 'Bulgur (çiğ)',
    synonyms: ['bulgur pilavı', 'pilavlık bulgur', 'köftelik bulgur'],
    category: 'grain',
    form: 'raw',
    per100g: { kcal: 342, protein: 12.3, carbs: 76, fat: 1.3, fiber: 12.5 },
    defaultTexture: 'granular',
    source: 'turkomp',
  },
  {
    id: 'pasta_raw',
    nameTr: 'Makarna (çiğ)',
    synonyms: ['makarna', 'spagetti', 'penne', 'erişte'],
    category: 'grain',
    form: 'raw',
    per100g: { kcal: 371, protein: 13, carbs: 75, fat: 1.5, fiber: 3.2 },
    defaultTexture: 'dense',
    source: 'usda',
  },
  {
    id: 'oats_raw',
    nameTr: 'Yulaf ezmesi (çiğ)',
    synonyms: ['yulaf', 'yulaflı', 'oats'],
    category: 'grain',
    form: 'raw',
    per100g: { kcal: 379, protein: 13.2, carbs: 67.7, fat: 6.5, fiber: 10.1 },
    defaultTexture: 'granular',
    source: 'usda',
  },
  {
    id: 'bread_white',
    nameTr: 'Beyaz ekmek',
    synonyms: ['ekmek', 'beyaz ekmek', 'somun', 'pide ekmeği'],
    category: 'grain',
    form: 'cooked',
    per100g: { kcal: 265, protein: 9, carbs: 49, fat: 3.2, fiber: 2.7 },
    defaultTexture: 'fluffy',
    source: 'usda',
  },
  {
    id: 'bread_whole_wheat',
    nameTr: 'Tam buğday ekmeği',
    synonyms: ['kepekli ekmek', 'tam buğday', 'tam tahıllı ekmek', 'kepekli'],
    category: 'grain',
    form: 'cooked',
    per100g: { kcal: 247, protein: 13, carbs: 41, fat: 3.4, fiber: 7 },
    defaultTexture: 'dense',
    source: 'usda',
  },
  {
    id: 'simit',
    nameTr: 'Simit',
    synonyms: ['simit', 'gevrek'],
    category: 'grain',
    form: 'cooked',
    per100g: { kcal: 339, protein: 11, carbs: 64, fat: 4.5, fiber: 3 },
    defaultTexture: 'dense',
    source: 'turkomp',
  },
  {
    id: 'lavash',
    nameTr: 'Lavaş',
    synonyms: ['lavaş', 'yufka', 'dürüm ekmeği'],
    category: 'grain',
    form: 'cooked',
    per100g: { kcal: 277, protein: 9, carbs: 56, fat: 1.5, fiber: 2 },
    defaultTexture: 'fluffy',
    source: 'turkomp',
  },

  // --- BAKLAGİLLER ---
  {
    id: 'lentil_red_raw',
    nameTr: 'Kırmızı mercimek (çiğ)',
    // 'mercimek çorbası' BURADA YOK — soup_lentil entry'sine bilerek bırakılmıştır.
    synonyms: ['kırmızı mercimek', 'kuru mercimek'],
    category: 'grain',
    form: 'raw',
    per100g: { kcal: 358, protein: 24, carbs: 63, fat: 1.1, fiber: 11 },
    defaultTexture: 'granular',
    source: 'usda',
  },
  {
    id: 'chickpea_raw',
    nameTr: 'Nohut (çiğ)',
    synonyms: ['nohut', 'leblebi', 'humus malzemesi'],
    category: 'grain',
    form: 'raw',
    per100g: { kcal: 364, protein: 19, carbs: 61, fat: 6, fiber: 17 },
    defaultTexture: 'granular',
    source: 'usda',
  },
  {
    id: 'beans_dry_raw',
    nameTr: 'Kuru fasulye (çiğ)',
    synonyms: ['kuru fasulye', 'fasulye', 'barbunya'],
    category: 'grain',
    form: 'raw',
    per100g: { kcal: 333, protein: 23, carbs: 60, fat: 0.8, fiber: 15 },
    defaultTexture: 'granular',
    source: 'usda',
  },

  // --- PROTEİNLER (et/balık, raw) ---
  {
    id: 'chicken_breast_raw',
    nameTr: 'Tavuk göğsü (çiğ)',
    synonyms: ['tavuk göğsü', 'tavuk', 'ızgara tavuk', 'piliç göğsü'],
    category: 'protein',
    form: 'raw',
    per100g: { kcal: 165, protein: 31, carbs: 0, fat: 3.6 },
    defaultTexture: 'dense',
    source: 'usda',
  },
  {
    id: 'chicken_thigh_raw',
    nameTr: 'Tavuk but (çiğ)',
    synonyms: ['tavuk but', 'tavuk baget', 'piliç but'],
    category: 'protein',
    form: 'raw',
    per100g: { kcal: 209, protein: 18, carbs: 0, fat: 15 },
    defaultTexture: 'dense',
    source: 'usda',
  },
  {
    id: 'beef_lean_raw',
    nameTr: 'Dana eti yağsız (çiğ)',
    synonyms: ['dana eti', 'biftek', 'bonfile', 'kuşbaşı'],
    category: 'protein',
    form: 'raw',
    per100g: { kcal: 217, protein: 26, carbs: 0, fat: 12 },
    defaultTexture: 'dense',
    source: 'usda',
  },
  {
    id: 'ground_beef_raw',
    nameTr: 'Dana kıyma (çiğ)',
    synonyms: ['kıyma', 'köfte', 'kasap köfte', 'izgara köfte'],
    category: 'protein',
    form: 'raw',
    per100g: { kcal: 250, protein: 26, carbs: 0, fat: 17 },
    defaultTexture: 'dense',
    source: 'usda',
  },
  {
    id: 'lamb_raw',
    nameTr: 'Kuzu eti (çiğ)',
    synonyms: ['kuzu eti', 'kuzu pirzola', 'kuzu şiş'],
    category: 'protein',
    form: 'raw',
    per100g: { kcal: 294, protein: 25, carbs: 0, fat: 21 },
    defaultTexture: 'dense',
    source: 'usda',
  },
  {
    id: 'salmon_raw',
    nameTr: 'Somon (çiğ)',
    synonyms: ['somon', 'somon balığı'],
    category: 'protein',
    form: 'raw',
    per100g: { kcal: 208, protein: 20, carbs: 0, fat: 13 },
    defaultTexture: 'dense',
    source: 'usda',
  },
  {
    id: 'sea_bass_raw',
    nameTr: 'Levrek (çiğ)',
    synonyms: ['levrek', 'levrek balığı', 'beyaz balık'],
    category: 'protein',
    form: 'raw',
    per100g: { kcal: 97, protein: 18, carbs: 0, fat: 2.5 },
    defaultTexture: 'dense',
    source: 'turkomp',
  },
  {
    id: 'anchovy_raw',
    nameTr: 'Hamsi (çiğ)',
    synonyms: ['hamsi', 'hamsi tava'],
    category: 'protein',
    form: 'raw',
    per100g: { kcal: 131, protein: 20, carbs: 0, fat: 4.8 },
    defaultTexture: 'dense',
    source: 'turkomp',
  },
  {
    id: 'egg_whole',
    nameTr: 'Yumurta',
    synonyms: ['yumurta', 'haşlanmış yumurta', 'omlet', 'menemen yumurtası', 'sahanda yumurta'],
    category: 'protein',
    form: 'cooked',
    per100g: { kcal: 155, protein: 13, carbs: 1.1, fat: 11 },
    defaultTexture: 'fluffy',
    source: 'usda',
  },

  // --- SÜT ÜRÜNLERİ ---
  {
    id: 'milk_whole',
    nameTr: 'Tam yağlı süt',
    synonyms: ['süt', 'tam yağlı süt', 'inek sütü'],
    category: 'dairy',
    form: 'cooked',
    per100g: { kcal: 61, protein: 3.2, carbs: 4.8, fat: 3.3 },
    defaultTexture: 'liquid',
    source: 'usda',
  },
  {
    id: 'yogurt_plain',
    nameTr: 'Yoğurt (tam yağlı)',
    synonyms: ['yoğurt', 'tam yağlı yoğurt', 'ev yoğurdu'],
    category: 'dairy',
    form: 'cooked',
    per100g: { kcal: 61, protein: 3.5, carbs: 4.7, fat: 3.3 },
    defaultTexture: 'amorphous',
    source: 'usda',
  },
  {
    id: 'yogurt_strained',
    nameTr: 'Süzme yoğurt',
    synonyms: ['süzme yoğurt', 'kaymaklı yoğurt'],
    category: 'dairy',
    form: 'cooked',
    per100g: { kcal: 97, protein: 9, carbs: 4, fat: 5 },
    defaultTexture: 'amorphous',
    source: 'turkomp',
  },
  {
    id: 'ayran',
    nameTr: 'Ayran',
    synonyms: ['ayran'],
    category: 'beverage',
    form: 'cooked',
    per100g: { kcal: 36, protein: 1.7, carbs: 2.5, fat: 2 },
    defaultTexture: 'liquid',
    source: 'turkomp',
  },
  {
    id: 'cheese_white',
    nameTr: 'Beyaz peynir',
    synonyms: ['beyaz peynir', 'feta', 'peynir', 'salamura peynir'],
    category: 'dairy',
    form: 'cooked',
    per100g: { kcal: 264, protein: 14, carbs: 4, fat: 21 },
    defaultTexture: 'dense',
    source: 'usda',
  },
  {
    id: 'cheese_kasar',
    nameTr: 'Kaşar peyniri',
    synonyms: ['kaşar', 'kaşar peyniri', 'sarı peynir'],
    category: 'dairy',
    form: 'cooked',
    per100g: { kcal: 358, protein: 25, carbs: 1.3, fat: 28 },
    defaultTexture: 'dense',
    source: 'turkomp',
  },

  // --- SEBZELER ---
  {
    id: 'tomato_raw',
    nameTr: 'Domates',
    synonyms: ['domates', 'kırmızı domates'],
    category: 'vegetable',
    form: 'raw',
    per100g: { kcal: 18, protein: 0.9, carbs: 3.9, fat: 0.2, fiber: 1.2 },
    defaultTexture: 'fluffy',
    source: 'usda',
  },
  {
    id: 'cucumber_raw',
    nameTr: 'Salatalık',
    synonyms: ['salatalık', 'hıyar'],
    category: 'vegetable',
    form: 'raw',
    per100g: { kcal: 16, protein: 0.7, carbs: 3.6, fat: 0.1, fiber: 0.5 },
    defaultTexture: 'fluffy',
    source: 'usda',
  },
  {
    id: 'lettuce_raw',
    nameTr: 'Marul',
    synonyms: ['marul', 'göbek marul', 'kıvırcık'],
    category: 'vegetable',
    form: 'raw',
    per100g: { kcal: 15, protein: 1.4, carbs: 2.9, fat: 0.2, fiber: 1.3 },
    defaultTexture: 'fluffy',
    source: 'usda',
  },
  {
    id: 'onion_raw',
    nameTr: 'Soğan',
    synonyms: ['soğan', 'kuru soğan', 'taze soğan'],
    category: 'vegetable',
    form: 'raw',
    per100g: { kcal: 40, protein: 1.1, carbs: 9.3, fat: 0.1, fiber: 1.7 },
    defaultTexture: 'dense',
    source: 'usda',
  },
  {
    id: 'pepper_green_raw',
    nameTr: 'Yeşil biber',
    synonyms: ['yeşil biber', 'biber', 'sivri biber', 'çarliston'],
    category: 'vegetable',
    form: 'raw',
    per100g: { kcal: 20, protein: 0.9, carbs: 4.6, fat: 0.2, fiber: 1.7 },
    defaultTexture: 'fluffy',
    source: 'usda',
  },
  {
    id: 'eggplant_raw',
    nameTr: 'Patlıcan',
    synonyms: ['patlıcan', 'kemer patlıcan'],
    category: 'vegetable',
    form: 'raw',
    per100g: { kcal: 25, protein: 1, carbs: 5.9, fat: 0.2, fiber: 3 },
    defaultTexture: 'fluffy',
    source: 'usda',
  },
  {
    id: 'potato_raw',
    nameTr: 'Patates (çiğ)',
    synonyms: ['patates', 'haşlanmış patates', 'patates kızartması', 'fırın patates'],
    category: 'vegetable',
    form: 'raw',
    per100g: { kcal: 77, protein: 2, carbs: 17, fat: 0.1, fiber: 2.2 },
    defaultTexture: 'dense',
    source: 'usda',
  },
  {
    id: 'spinach_raw',
    nameTr: 'Ispanak (çiğ)',
    synonyms: ['ıspanak', 'spinach'],
    category: 'vegetable',
    form: 'raw',
    per100g: { kcal: 23, protein: 2.9, carbs: 3.6, fat: 0.4, fiber: 2.2 },
    defaultTexture: 'fluffy',
    source: 'usda',
  },
  {
    id: 'zucchini_raw',
    nameTr: 'Kabak',
    synonyms: ['kabak', 'sakız kabağı', 'yeşil kabak'],
    category: 'vegetable',
    form: 'raw',
    per100g: { kcal: 17, protein: 1.2, carbs: 3.1, fat: 0.3, fiber: 1 },
    defaultTexture: 'fluffy',
    source: 'usda',
  },
  {
    id: 'carrot_raw',
    nameTr: 'Havuç',
    synonyms: ['havuç'],
    category: 'vegetable',
    form: 'raw',
    per100g: { kcal: 41, protein: 0.9, carbs: 9.6, fat: 0.2, fiber: 2.8 },
    defaultTexture: 'dense',
    source: 'usda',
  },

  // --- MEYVELER ---
  {
    id: 'apple_raw',
    nameTr: 'Elma',
    synonyms: ['elma', 'kırmızı elma', 'yeşil elma'],
    category: 'fruit',
    form: 'raw',
    per100g: { kcal: 52, protein: 0.3, carbs: 14, fat: 0.2, fiber: 2.4 },
    defaultTexture: 'dense',
    source: 'usda',
  },
  {
    id: 'banana_raw',
    nameTr: 'Muz',
    synonyms: ['muz'],
    category: 'fruit',
    form: 'raw',
    per100g: { kcal: 89, protein: 1.1, carbs: 23, fat: 0.3, fiber: 2.6 },
    defaultTexture: 'dense',
    source: 'usda',
  },
  {
    id: 'orange_raw',
    nameTr: 'Portakal',
    synonyms: ['portakal'],
    category: 'fruit',
    form: 'raw',
    per100g: { kcal: 47, protein: 0.9, carbs: 12, fat: 0.1, fiber: 2.4 },
    defaultTexture: 'fluffy',
    source: 'usda',
  },
  {
    id: 'grapes_raw',
    nameTr: 'Üzüm',
    synonyms: ['üzüm', 'siyah üzüm', 'yeşil üzüm'],
    category: 'fruit',
    form: 'raw',
    per100g: { kcal: 69, protein: 0.7, carbs: 18, fat: 0.2, fiber: 0.9 },
    defaultTexture: 'dense',
    source: 'usda',
  },
  {
    id: 'strawberry_raw',
    nameTr: 'Çilek',
    synonyms: ['çilek'],
    category: 'fruit',
    form: 'raw',
    per100g: { kcal: 32, protein: 0.7, carbs: 7.7, fat: 0.3, fiber: 2 },
    defaultTexture: 'fluffy',
    source: 'usda',
  },
  {
    id: 'watermelon_raw',
    nameTr: 'Karpuz',
    synonyms: ['karpuz'],
    category: 'fruit',
    form: 'raw',
    per100g: { kcal: 30, protein: 0.6, carbs: 7.6, fat: 0.2, fiber: 0.4 },
    defaultTexture: 'fluffy',
    source: 'usda',
  },

  // --- KURUYEMİŞ & YAĞ ---
  {
    id: 'walnut_raw',
    nameTr: 'Ceviz',
    synonyms: ['ceviz', 'ceviz içi'],
    category: 'fat',
    form: 'raw',
    per100g: { kcal: 654, protein: 15, carbs: 14, fat: 65, fiber: 6.7 },
    defaultTexture: 'granular',
    source: 'usda',
  },
  {
    id: 'almond_raw',
    nameTr: 'Badem',
    synonyms: ['badem'],
    category: 'fat',
    form: 'raw',
    per100g: { kcal: 579, protein: 21, carbs: 22, fat: 50, fiber: 12 },
    defaultTexture: 'granular',
    source: 'usda',
  },
  {
    id: 'olive_oil',
    nameTr: 'Zeytinyağı',
    synonyms: ['zeytinyağı', 'sızma zeytinyağı'],
    category: 'fat',
    form: 'cooked',
    per100g: { kcal: 884, protein: 0, carbs: 0, fat: 100 },
    defaultTexture: 'liquid',
    source: 'usda',
  },
  {
    id: 'butter',
    nameTr: 'Tereyağı',
    synonyms: ['tereyağı', 'tereyag', 'tereyağ'],
    category: 'fat',
    form: 'cooked',
    per100g: { kcal: 717, protein: 0.9, carbs: 0.1, fat: 81 },
    defaultTexture: 'dense',
    source: 'usda',
  },
  {
    id: 'olive_black',
    nameTr: 'Siyah zeytin',
    synonyms: ['zeytin', 'siyah zeytin', 'sele zeytin'],
    category: 'fat',
    form: 'cooked',
    per100g: { kcal: 115, protein: 0.8, carbs: 6.3, fat: 11 },
    defaultTexture: 'dense',
    source: 'usda',
  },

  // --- ÇORBA & KARIŞIK ---
  {
    id: 'soup_lentil',
    nameTr: 'Mercimek çorbası (pişmiş)',
    synonyms: ['mercimek çorbası', 'kırmızı mercimek çorbası', 'ezogelin çorbası'],
    category: 'mixed',
    form: 'cooked',
    per100g: { kcal: 60, protein: 3.2, carbs: 9, fat: 1.4, fiber: 1.8 },
    defaultTexture: 'liquid',
    source: 'turkomp',
  },
  {
    id: 'soup_chicken',
    nameTr: 'Tavuk çorbası (pişmiş)',
    synonyms: ['tavuk çorbası', 'düğün çorbası'],
    category: 'mixed',
    form: 'cooked',
    per100g: { kcal: 38, protein: 2.5, carbs: 4, fat: 1.3 },
    defaultTexture: 'liquid',
    source: 'turkomp',
  },
  {
    id: 'soup_tarhana',
    nameTr: 'Tarhana çorbası (pişmiş)',
    synonyms: ['tarhana çorbası', 'tarhana'],
    category: 'mixed',
    form: 'cooked',
    per100g: { kcal: 55, protein: 2.8, carbs: 9.5, fat: 1.1 },
    defaultTexture: 'liquid',
    source: 'turkomp',
  },

  // --- TATLI & İÇECEK ---
  {
    id: 'baklava',
    nameTr: 'Baklava',
    synonyms: ['baklava', 'cevizli baklava', 'fıstıklı baklava'],
    category: 'sweet',
    form: 'cooked',
    per100g: { kcal: 428, protein: 5.5, carbs: 49, fat: 24 },
    defaultTexture: 'dense',
    source: 'turkomp',
  },
  {
    id: 'rice_pudding',
    nameTr: 'Sütlaç',
    synonyms: ['sütlaç'],
    category: 'sweet',
    form: 'cooked',
    per100g: { kcal: 134, protein: 3.2, carbs: 23, fat: 3 },
    defaultTexture: 'amorphous',
    source: 'turkomp',
  },
  {
    id: 'tea_black',
    nameTr: 'Çay (sade)',
    synonyms: ['çay', 'siyah çay', 'demli çay'],
    category: 'beverage',
    form: 'cooked',
    per100g: { kcal: 1, protein: 0, carbs: 0.2, fat: 0 },
    defaultTexture: 'liquid',
    source: 'usda',
  },
  {
    id: 'turkish_coffee',
    nameTr: 'Türk kahvesi (sade)',
    synonyms: ['türk kahvesi', 'kahve', 'sade kahve'],
    category: 'beverage',
    form: 'cooked',
    per100g: { kcal: 2, protein: 0.1, carbs: 0, fat: 0 },
    defaultTexture: 'liquid',
    source: 'turkomp',
  },
];

// Hızlı erişim için id index'i
export const COMPOSITION_BY_ID: Record<string, CompositionEntry> = Object.fromEntries(
  FOOD_COMPOSITION.map((e) => [e.id, e])
);
